server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /output/ {
        alias /usr/share/nginx/output/;
        add_header Accept-Ranges bytes;
        autoindex on;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /output/broadcast_data.json {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        expires 0;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}