server {
    listen 80;
    root /usr/share/nginx/html;

    # Serve the frontend at the root
    location / {
        index frontend/index.html;
        try_files $uri $uri/ /frontend/index.html;
    }

    # Explicitly map the output folder for audio and json data
    location /output/ {
        alias /usr/share/nginx/html/output/;
        add_header Access-Control-Allow-Origin *;
    }
}
